name: publish

on: 
  workflow_dispatch:
    inputs:
      pull_request:
        description: Pull request number
        default: "0"
        required: true
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PR_NUMBER: ${{ github.event.inputs.pull_request }}
jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - id: repository
      uses: ASzc/change-string-case-action@v2
      with:
        string: ${{ github.repository }}    
    # - name: Downcase repo name
    #   run: | 
    #     echo "GITHUB_REPOSITORY_LOWER_CASE=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}     
    - uses: actions/checkout@v3
      with:
        ref: refs/pull/${{ PR_NUMBER }}/head 

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push docker image to github registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        file: ./Dockerfile
        tags: ${{ env.REGISTRY }}/${{ steps.repository.outputs.lowercase }}:pr${{ PR_NUMBER }}

