name: publish

on: 
  workflow_dispatch:
    inputs:
      pull_request:
        description: Pull request number
        default: "0"
        required: true
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - name: Downcase repo name
      run: | 
        echo "GITHUB_REPOSITORY_LOWER_CASE=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}     
    - uses: actions/checkout@v3
      with:
        ref: refs/pull/${{ github.event.inputs.pull_request }}/head 

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}-${{ github.event.inputs.pull_request }}
    - name: Build and push docker image to github registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        file: ./Dockerfile
        tags: ${{ env.REGISTRY }}/${{ env.GITHUB_REPOSITORY_LOWER_CASE }}:pr${{ github.event.inputs.pull_request }}
        labels: ${{ steps.meta.outputs.labels }}

