name: publish

on: 
  workflow_dispatch:
    inputs:
      pull_request:
        description: Pull request number
        default: "0"
        required: true
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.pull_request }}

    # - name: Login to GitHub Container Registry
    #   uses: docker/login-action@v1
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}

    # - name: Build the hello-world Docker image
    #   run: |
    #     docker build . --tag ghcr.io/alexf4dev/hello-world:latest
    #     docker run ghcr.io/alexf4dev/hello-world:latest
    #     docker push ghcr.io/alexf4dev/hello-world:latest

